insert into center(id,description,name,rating,address) values (1,"The best bank","Blood type",5,"Milenka Grcica 10")
insert into center(id,description,name,rating,address) values (2,"Almost the best bank","Transfusion",4.13,"Milenka Milosa 12")
insert into center(id,description,name,rating,address) values (3,"Mid best bank","Redd",4.3,"Janka Cmelika 57")
insert into center(id,description,name,rating,address) values (4,"Not the best bank","Blood--",3.14,"Svetosavska 1")
insert into center(id,description,name,rating,address) values (5,"Certainly not the best bank","Blood",2,"Narodnih heroja 4")
insert into loyalty values (1,"Very good category",5)
insert into registered_user values(1,"Milenka Grcica 2","0-","Novi Sad","Serbia","email@email.com","M","Info","1234567890123","Imenko","Engineer","123456","0063111222","Prezimic",1)